-- Manual SQL migration for the Agent Control Plane.
-- IMPORTANT: This file is intended to be executed manually by the operator.
-- It replaces the invalid full-schema output previously generated by drizzle-kit.

-- 1. Enums
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agent_mode') THEN
    CREATE TYPE agent_mode AS ENUM ('dry-run', 'manual', 'semi-automatic', 'autonomous');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agent_trigger_type') THEN
    CREATE TYPE agent_trigger_type AS ENUM ('manual', 'schedule', 'event');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agent_run_status') THEN
    CREATE TYPE agent_run_status AS ENUM ('queued', 'running', 'waiting-approval', 'completed', 'failed', 'cancelled', 'rejected');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agent_action_kind') THEN
    CREATE TYPE agent_action_kind AS ENUM ('read', 'notify', 'generate-script', 'write');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agent_action_status') THEN
    CREATE TYPE agent_action_status AS ENUM ('planned', 'pending-approval', 'approved', 'executed', 'blocked', 'skipped', 'failed', 'rejected');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_status') THEN
    CREATE TYPE approval_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_channel') THEN
    CREATE TYPE notification_channel AS ENUM ('email', 'in-app');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_status') THEN
    CREATE TYPE notification_status AS ENUM ('pending', 'sent', 'failed', 'cancelled');
  END IF;
END $$;

-- 2. Core tables
CREATE TABLE IF NOT EXISTS "agent_definitions" (
  "id" serial PRIMARY KEY NOT NULL,
  "agent_key" varchar(80) NOT NULL,
  "name" varchar(150) NOT NULL,
  "description" text,
  "version" varchar(30) DEFAULT '1.0.0' NOT NULL,
  "default_mode" "agent_mode" DEFAULT 'dry-run' NOT NULL,
  "supports_manual_trigger" boolean DEFAULT true NOT NULL,
  "supports_schedule" boolean DEFAULT false NOT NULL,
  "supports_event_trigger" boolean DEFAULT false NOT NULL,
  "owner" varchar(120),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "agent_config" (
  "id" serial PRIMARY KEY NOT NULL,
  "agent_definition_id" integer NOT NULL,
  "is_enabled" boolean DEFAULT false NOT NULL,
  "mode" "agent_mode" DEFAULT 'dry-run' NOT NULL,
  "schedule_expression" varchar(120),
  "timeout_seconds" integer DEFAULT 300 NOT NULL,
  "max_retries" integer DEFAULT 0 NOT NULL,
  "approval_required_for_writes" boolean DEFAULT true NOT NULL,
  "notification_recipients" jsonb,
  "trigger_filters" jsonb,
  "config_json" jsonb,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "agent_config_agent_definition_id_agent_definitions_id_fk"
    FOREIGN KEY ("agent_definition_id") REFERENCES "agent_definitions"("id") ON DELETE no action ON UPDATE no action
);

CREATE TABLE IF NOT EXISTS "run_history" (
  "id" serial PRIMARY KEY NOT NULL,
  "agent_definition_id" integer NOT NULL,
  "agent_config_id" integer,
  "run_key" varchar(120) NOT NULL,
  "trigger_type" "agent_trigger_type" NOT NULL,
  "trigger_source" varchar(120) NOT NULL,
  "mode" "agent_mode" NOT NULL,
  "status" "agent_run_status" DEFAULT 'queued' NOT NULL,
  "initiated_by" varchar(120),
  "idempotency_key" varchar(150),
  "correlation_id" varchar(150),
  "summary" text,
  "payload" jsonb,
  "result_json" jsonb,
  "error_code" varchar(80),
  "error_message" text,
  "started_at" timestamp,
  "finished_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "run_history_agent_definition_id_agent_definitions_id_fk"
    FOREIGN KEY ("agent_definition_id") REFERENCES "agent_definitions"("id") ON DELETE no action ON UPDATE no action,
  CONSTRAINT "run_history_agent_config_id_agent_config_id_fk"
    FOREIGN KEY ("agent_config_id") REFERENCES "agent_config"("id") ON DELETE no action ON UPDATE no action
);

CREATE TABLE IF NOT EXISTS "action_logs" (
  "id" serial PRIMARY KEY NOT NULL,
  "run_history_id" integer NOT NULL,
  "action_key" varchar(150) NOT NULL,
  "kind" "agent_action_kind" NOT NULL,
  "status" "agent_action_status" DEFAULT 'planned' NOT NULL,
  "summary" text NOT NULL,
  "target_type" varchar(80),
  "target_id" varchar(120),
  "requires_approval" boolean DEFAULT false NOT NULL,
  "requires_human_execution" boolean DEFAULT false NOT NULL,
  "generated_artifact_path" text,
  "action_payload" jsonb,
  "result_payload" jsonb,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "action_logs_run_history_id_run_history_id_fk"
    FOREIGN KEY ("run_history_id") REFERENCES "run_history"("id") ON DELETE no action ON UPDATE no action
);

CREATE TABLE IF NOT EXISTS "approvals" (
  "id" serial PRIMARY KEY NOT NULL,
  "run_history_id" integer NOT NULL,
  "action_log_id" integer,
  "requested_by_user_id" integer,
  "decided_by_user_id" integer,
  "status" "approval_status" DEFAULT 'pending' NOT NULL,
  "summary" text NOT NULL,
  "reason" text,
  "requested_at" timestamp DEFAULT now() NOT NULL,
  "decided_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "approvals_run_history_id_run_history_id_fk"
    FOREIGN KEY ("run_history_id") REFERENCES "run_history"("id") ON DELETE no action ON UPDATE no action,
  CONSTRAINT "approvals_action_log_id_action_logs_id_fk"
    FOREIGN KEY ("action_log_id") REFERENCES "action_logs"("id") ON DELETE no action ON UPDATE no action,
  CONSTRAINT "approvals_requested_by_user_id_users_id_fk"
    FOREIGN KEY ("requested_by_user_id") REFERENCES "users"("id") ON DELETE no action ON UPDATE no action,
  CONSTRAINT "approvals_decided_by_user_id_users_id_fk"
    FOREIGN KEY ("decided_by_user_id") REFERENCES "users"("id") ON DELETE no action ON UPDATE no action
);

CREATE TABLE IF NOT EXISTS "notifications" (
  "id" serial PRIMARY KEY NOT NULL,
  "agent_definition_id" integer,
  "run_history_id" integer,
  "approval_id" integer,
  "channel" "notification_channel" NOT NULL,
  "status" "notification_status" DEFAULT 'pending' NOT NULL,
  "recipient" varchar(255) NOT NULL,
  "subject" varchar(200),
  "message" text NOT NULL,
  "metadata" jsonb,
  "sent_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "notifications_agent_definition_id_agent_definitions_id_fk"
    FOREIGN KEY ("agent_definition_id") REFERENCES "agent_definitions"("id") ON DELETE no action ON UPDATE no action,
  CONSTRAINT "notifications_run_history_id_run_history_id_fk"
    FOREIGN KEY ("run_history_id") REFERENCES "run_history"("id") ON DELETE no action ON UPDATE no action,
  CONSTRAINT "notifications_approval_id_approvals_id_fk"
    FOREIGN KEY ("approval_id") REFERENCES "approvals"("id") ON DELETE no action ON UPDATE no action
);

CREATE TABLE IF NOT EXISTS "trigger_metadata" (
  "id" serial PRIMARY KEY NOT NULL,
  "agent_definition_id" integer NOT NULL,
  "trigger_type" "agent_trigger_type" NOT NULL,
  "trigger_key" varchar(150) NOT NULL,
  "trigger_source" varchar(120),
  "metadata" jsonb,
  "last_fired_at" timestamp,
  "next_scheduled_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "trigger_metadata_agent_definition_id_agent_definitions_id_fk"
    FOREIGN KEY ("agent_definition_id") REFERENCES "agent_definitions"("id") ON DELETE no action ON UPDATE no action
);

-- 3. Indexes
CREATE UNIQUE INDEX IF NOT EXISTS "agent_definitions_agent_key_uq" ON "agent_definitions" USING btree ("agent_key");
CREATE INDEX IF NOT EXISTS "agent_definitions_agent_key_idx" ON "agent_definitions" USING btree ("agent_key");

CREATE INDEX IF NOT EXISTS "agent_config_agent_definition_id_idx" ON "agent_config" USING btree ("agent_definition_id");

CREATE UNIQUE INDEX IF NOT EXISTS "run_history_run_key_uq" ON "run_history" USING btree ("run_key");
CREATE INDEX IF NOT EXISTS "run_history_agent_definition_id_idx" ON "run_history" USING btree ("agent_definition_id");
CREATE INDEX IF NOT EXISTS "run_history_status_idx" ON "run_history" USING btree ("status");
CREATE INDEX IF NOT EXISTS "run_history_created_at_idx" ON "run_history" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "run_history_idempotency_key_idx" ON "run_history" USING btree ("idempotency_key");

CREATE INDEX IF NOT EXISTS "action_logs_run_history_id_idx" ON "action_logs" USING btree ("run_history_id");
CREATE INDEX IF NOT EXISTS "action_logs_action_key_idx" ON "action_logs" USING btree ("action_key");
CREATE INDEX IF NOT EXISTS "action_logs_status_idx" ON "action_logs" USING btree ("status");

CREATE INDEX IF NOT EXISTS "approvals_run_history_id_idx" ON "approvals" USING btree ("run_history_id");
CREATE INDEX IF NOT EXISTS "approvals_action_log_id_idx" ON "approvals" USING btree ("action_log_id");
CREATE INDEX IF NOT EXISTS "approvals_status_idx" ON "approvals" USING btree ("status");
CREATE INDEX IF NOT EXISTS "approvals_requested_at_idx" ON "approvals" USING btree ("requested_at");

CREATE INDEX IF NOT EXISTS "notifications_run_history_id_idx" ON "notifications" USING btree ("run_history_id");
CREATE INDEX IF NOT EXISTS "notifications_status_idx" ON "notifications" USING btree ("status");
CREATE INDEX IF NOT EXISTS "notifications_created_at_idx" ON "notifications" USING btree ("created_at");

CREATE INDEX IF NOT EXISTS "trigger_metadata_agent_definition_id_idx" ON "trigger_metadata" USING btree ("agent_definition_id");
CREATE INDEX IF NOT EXISTS "trigger_metadata_trigger_key_idx" ON "trigger_metadata" USING btree ("trigger_key");
CREATE INDEX IF NOT EXISTS "trigger_metadata_created_at_idx" ON "trigger_metadata" USING btree ("created_at");